weights: models/checkpoints/yolov5_multilabel_736_736_15_11_21.pt
device: 0 # cuda device, i.e. 0 or 0,1,2,3 or cpu
input_size: [736, 736] # inference size h,w
nms_conf_thres: 0.01  # confidence threshold
iou_thres: 0.3  # NMS IOU threshold
iou_thres_post: 0.8
max_det: 1000  # maximum detections per image
classes: null  # filter by class: --class 0, or --class 0 2 3
agnostic_nms: False # class-agnostic NMS
augment: False  # augmented inference
half: True  # use FP16 half-precision inference
classify: False  # False
conf_thres_list:  [0.5, 0.5, 0.2, 0.5, 0.5, 0.2, 0.5, 0.5, 0.2, 0.5]
suffixes: ['.pt', '.onnx']
stride: 32
